server:
  port: 8092

spring:
  application:
    name: kafka-streams-app
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: event-processor
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000

logging:
  level:
    com.kafka.training: DEBUG
    org.apache.kafka.streams: INFO
    org.apache.kafka: WARN
