spring:
  application:
    name: scalable-consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: message-consumer-group

kafka:
  consumer:
    topic: messages

logging:
  level:
    com.kafka.training: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
